### ISSUE TITLE
Investigate if this extension is still useful in Firefox >= 58

### ISSUE THREAD

**Issue by clemstoquart** [clemstoquart/webextension-json-mime-type#14]
https://bugzilla.mozilla.org/show_bug.cgi?id=1388335

**Comment by ymarillet** [comment]
hi, the extension is actually still viable in FF 58+, I am using a different json viewer from the native one (https://addons.mozilla.org/fr/firefox/addon/kisad-json-viewer/) but mozilla's "fix" binds us to their json viewer. Could you consider to re-enable your extension ?

**Comment by clemstoquart** [comment]
Hi @ymarillet 
I was not aware of that. Thanks for letting me know :)
No problem I will remove the strict max version.

**Comment by luispabon** [comment]
Also fixes firefox issues with content types other than plain `application/json`, like JSONAPI's `application/vnd.api+json`
